### ISSUE TITLE
Broken ZooKeeper link

### ISSUE THREAD

**Issue by frankshearar** [mixu/distsysbook#25]
Currently the reference for ZooKeeper points to http://research.yahoo.com/pub/3280, which no longer hosts the paper. How about this reference?: http://www.usenix.org/event/usenix10/tech/full_papers/Hunt.pdf

(If I was sure of the appropriate replacement URL I'd just issue a PR.)

**Comment by mixu** [comment]
fixed in 87a017fbb7fd5da4d2ab417f0f0ec682e99a03a8
